name: Biuld and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
      
  deploy: 
   runs-on: ubuntu-latest
   steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.srv-cpv7amhu0jms73am29e0 }}
          api-key: ${{ secrets.rnd_mFfWROqLJexsc5USe1jMn4oCPPZL}}
          wait-for-success: true

  
